{
 "title": "Measurement logger",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "METERS",
    "label": "Meters",
    "query": "SELECT DISTINCT(device_id) FROM elec_measurement;"
   }
  ]
 },
 "panels": [
  {
   "title": "Grid Power",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  value AS \"P+\"\nFROM elec_measurement\nWHERE\n  $__timeFilter(\"time\") AND\n  obis_name = 'P+' AND\n  device_id = '$METERS' \nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  value AS \"P-\"\nFROM elec_measurement\nWHERE\n  $__timeFilter(\"time\") AND\n  obis_name = 'P-' AND\n  device_id = '$METERS' \nORDER BY 1"
    }
   ]
  },
  {
   "title": "Energy",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  value AS \"A+ T1\"\nFROM elec_measurement\nWHERE\n  $__timeFilter(\"time\") AND\n  obis_name = 'A+(T1)' AND\n  device_id = '$METERS' \nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  value AS \"A+ T2\"\nFROM elec_measurement\nWHERE\n  $__timeFilter(\"time\") AND\n  obis_name = 'A+(T2)' AND\n  device_id = '$METERS' \nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  -value AS \"A- T1\"\nFROM elec_measurement\nWHERE\n  $__timeFilter(\"time\") AND\n  obis_name = 'A-(T1)' AND\n  device_id = '$METERS' \nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  -value AS \"A- T2\"\nFROM elec_measurement\nWHERE\n  $__timeFilter(\"time\") AND\n  obis_name = 'A-(T2)' AND\n  device_id = '$METERS' \nORDER BY 1"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  value AS \"L1\"\nFROM elec_measurement\nWHERE\n  $__timeFilter(\"time\") AND\n  obis_name = 'U(L1)' AND\n  device_id = '$METERS' \nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  value AS \"L2\"\nFROM elec_measurement\nWHERE\n  $__timeFilter(\"time\") AND\n  obis_name = 'U(L2)' AND\n  device_id = '$METERS' \nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  value AS \"L3\"\nFROM elec_measurement\nWHERE\n  $__timeFilter(\"time\") AND\n  obis_name = 'U(L3)' AND\n  device_id = '$METERS' \nORDER BY 1"
    }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  value AS \"L1\"\nFROM elec_measurement\nWHERE\n  $__timeFilter(\"time\") AND\n  obis_name = 'I(L1)' AND\n  device_id = '$METERS' \nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  value AS \"L2\"\nFROM elec_measurement\nWHERE\n  $__timeFilter(\"time\") AND\n  obis_name = 'I(L2)' AND\n  device_id = '$METERS' \nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  value AS \"L3\"\nFROM elec_measurement\nWHERE\n  $__timeFilter(\"time\") AND\n  obis_name = 'I(L3)' AND\n  device_id = '$METERS' \nORDER BY 1"
    }
   ]
  }
 ]
}